### ISSUE TITLE
[Mobile] Shift Klarna logo + copy up higher - iOS - Safari

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#10]
Can we move type up higher and make room for our larger pillar/prize as well on mobile?

![mobile_logo_text_layout](https://user-images.githubusercontent.com/20975193/83554023-fa67bc80-a4c0-11ea-84e9-dcb65bd9d98a.jpg)

@friedman74 @janell-f

**Comment by zerostyle** [comment]
Done
