### ISSUE TITLE
[Flag] Smooothen

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#100]
Is there anything we can do to smoothen out the loop of the flag animation?

**Comment by scottiedarko** [comment]
One thing that could help is shortening and speeding up the loop both for animation and compression purposes. @zerostyle can you optimize this sequence for better web compression and make a smaller version for mobile? Let me know if you want our help to do that at lower image  quality? Hoping this loops cleaner.

@janell-f @friedman74 

[FLAG_v4.zip](https://github.com/wildlifela/klarna-smoooth-shoppability/files/4806039/FLAG_v4.zip)
