### ISSUE TITLE
[Price Check] OG Price Update

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#103]
Hey Josh, can we fly through and update the prices? 

Some of the amounts have been updated (I can't see which ones, the pre-48 hours is on dev), and make sure they're formatted like they are in the deck: 

IE $1498 would be $1,498.00

https://docs.google.com/spreadsheets/d/1LEpkQ6b51FqJwYbZdzn1nRibDkTkPGQxLFWdU4DmAl8/edit#gid=1961947145

**Comment by zerostyle** [comment]
Do you want the products in this order too?

**Comment by janell-f** [comment]
There's no preference, we can keep rolling as is.

**Comment by janell-f** [comment]
[famous last words]
