### ISSUE TITLE
[Copy] Email sign up

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#108]
Instead of: 
**Yes, let's stay in touch**

It will be:
**Let's stay in touch?** 

<img width="182" alt="Screen Shot 2020-06-19 at 6 32 55 PM" src="https://user-images.githubusercontent.com/58711192/85188510-f62af580-b25b-11ea-82c3-fd356ffbbcd9.png">

**Comment by friedman74** [comment]
Should "email" be "Email" here as well?
