### ISSUE TITLE
[Question] Rules URL : smoooth.klarna.com/rules 

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#109]
Can we make the link for the rules smoooth.klarna.com/rules ? Assuming the same would apply for legal. 

Let me know what you think! I think currently the rules are an overlay, not a separate page.

Ultimately, PL can't give us the final legal language until they can insert a URL for the rules in the legal language, so I'm trying to find the path of least resistance.

**Comment by zerostyle** [comment]
We can, but we are not saving app state currently. Without the modal, the page resets to the beginning of the experience. We can have both the page and the modal, but I think showing a modal there is a good solve. The other option is to save the more of the app state, but that takes time too.

**Comment by friedman74** [comment]
What's the easiest solve then to allow them to link to the legal? Do we just launch it as a standalone page in a new tab so that we don't have to mess with the app state and structure at all?

**Comment by janell-f** [comment]
I think so.  @pr1ntr might need to weigh in, too. 

Maybe a separate page is the way to go? They're going to insist on a URL, and they're not giving the legal the final approval to be shared with us without that link.

**Comment by zerostyle** [comment]
Opening in a blank page works for me.

**Comment by janell-f** [comment]
Awesome, thanks! I'll confirm the final URL for legal, but rules are: smoooth.klarna.com/rules
