### ISSUE TITLE
[Meta] Meta for SEO

### ISSUE THREAD

**Issue by zerostyle** [wildlifela/klarna-smoooth-shoppability#110]
Do we want to add a site description, and tags?

**Comment by janell-f** [comment]
Yuuuup, pushing for it with Mirimar.  Hoping to have it by EOD today

**Comment by janell-f** [comment]
Title and Description:

**TITLE:** The 48 Hr. Smoooth Room - By Klarna.
**DESCRIPTION:**  Enter for your chance to win something smoooth, from Klarna - the new online shopping app from Sweden. Hurry, time is running out. 

Photo pending.

**Comment by zerostyle** [comment]
Title and description on in.

**Comment by janell-f** [comment]
aaaaand photo! 

![Preview](https://user-images.githubusercontent.com/58711192/85491727-df044480-b588-11ea-89bc-1860ccc836e9.png)
