### ISSUE TITLE
[Copy] Swipe -or- Click? 

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#111]
On Desktop should Swipe say Click? 

![Screen Shot 2020-06-22 at 2 50 01 PM](https://user-images.githubusercontent.com/58711192/85339196-7d64ad00-b498-11ea-99bf-14bbbf07d19e.png)

**Comment by zerostyle** [comment]
It does swipe on desktop too.

**Comment by janell-f** [comment]
Right, should it say **click to shop** on desktop?

**Comment by friedman74** [comment]
Click and drag to shop... perhaps?
