### ISSUE TITLE
[Deep Links]

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#115]
Mirimar just provided their deep link preferences for each of the prizes: 

- [ ] smoooth.klarna.com/aquarium
- [ ] smoooth.klarna.com/sonos-speakers
- [ ] smoooth.klarna.com/fender-strat
- [ ] smoooth.klarna.com/surfwheel
- [ ] smoooth.klarna.com/anine-bing-fanny-bag
- [ ] smoooth.klarna.com//dyson-airwrap
- [ ] smoooth.klarna.com/hydrow-rower
- [ ] smoooth.klarna.com/creagh-satchel
- [ ] smoooth.klarna.com/gaming-chair
- [ ] smoooth.klarna.com/telescope
- [ ] smoooth.klarna.com/kayak/
- [ ] smoooth.klarna.com/yeti-cooler
- [ ] smoooth.klarna.com/lunya-set
- [ ] smoooth.klarna.com/mejuri-bangle
- [ ] smoooth.klarna.com/adidas-zx-4000

**Comment by friedman74** [comment]
` smoooth.klarna.com/adidas-ZX-4000`

this is the only one with any capital letters in it, can we update to `smoooth.klarna.com/adidas-zx-4000` ?

**Comment by janell-f** [comment]
Yes, updated it in the checklist.  thanks for catching!
