### ISSUE TITLE
[Pixels for Prizes]

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#118]
Related to #23 
Now that we have individual prize links, we'll need to make sure we're tracking those too: 

The idea is to send actual URLs a visitor has visited. Not hard code the text pageURLs into the tag. 

![unnamed](https://user-images.githubusercontent.com/58711192/85462014-e2cca280-b559-11ea-9710-36d2f3b25456.png)

"How to implement the event snippet:
The event snippet section should be placed on pages with events you’re tracking, after the global snippet.
Send page URL in 'u13': '[URLs]' - so we can separate URLs on our side"

[Google ads - US.txt](https://github.com/wildlifela/klarna-smoooth-shoppability/files/4821927/Google.ads.-.US.txt)

**Comment by pr1ntr** [comment]
@janell-f what is the goal of this? If we have an actual subdir for each prize (ie, smoooth.klarna.com/flamingo) then we can just fire a pageview anytime the subdir changes. I don't know what u13 or anything like that means here.

**Comment by janell-f** [comment]
I'm not sure how they're tracking, but these were the exact directions they provided.
