### ISSUE TITLE
[Mobile] Not Displaying Responsively 

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#12]
**Pixel 2 XL
Chrome** 

seeing this: 

![Screenshot_20200602-184532](https://user-images.githubusercontent.com/58711192/83588749-e6df4480-a506-11ea-94c6-262fa2a9468d.png)

jake, scott, tagging you if you see this as well.

**Comment by scottiedarko** [comment]
Looks ok on iPhone
![CF1252B0-E453-421A-9C71-F59E48D07462](https://user-images.githubusercontent.com/20975193/83589250-1e9abc00-a508-11ea-964f-496a470b1cb7.png)

**Comment by zerostyle** [comment]
Are you seeing that on an actual device?

**Comment by janell-f** [comment]
@zerostyle Yeah, an actual device - a pixel2 xl. 

@pr1ntr are you seeing this display properly?
