### ISSUE TITLE
[End of Carousel]

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#127]
Update this headline to: 

Can't decide? Take another look, friend.

Remove the black background from the white arrow.
![Screen Shot 2020-06-24 at 10 15 15 AM](https://user-images.githubusercontent.com/58711192/85626876-897c7600-b622-11ea-801b-4f33dd64562f.png)

**Comment by friedman74** [comment]
Do we have this as a vector asset? It's a little crunchy atm as well

**Comment by zerostyle** [comment]
This image renders on canvas. I'm not sure how to make it sharper. These vector type graphics seem better suited for the dom.

**Comment by friedman74** [comment]
Gotcha, it’s not a glaring issue, was just checking if it good be sharpened further. No prob.
