### ISSUE TITLE
[Prizes] Getting cut off 

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#128]
Viewing on just my laptop/smaller browser sizes, it looks like some prizes are getting cut off - the strat and the pajamas: 

<img width="1552" alt="Screen Shot 2020-06-24 at 3 18 19 PM" src="https://user-images.githubusercontent.com/58711192/85633552-4cb67c00-b62e-11ea-9b83-494d04894594.png">
<img width="1552" alt="Screen Shot 2020-06-24 at 3 19 44 PM" src="https://user-images.githubusercontent.com/58711192/85633567-52ac5d00-b62e-11ea-999c-f48ed18ae784.png">

**Comment by zerostyle** [comment]
Fixed
