### ISSUE TITLE
[Copy] Updates

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#130]
- [x]  Change "Rules and conditions" to "Official rules"

- [x] Rad Aquarium | Change price to $1,100.00

- [x] Dope Gaming Chair	| Change price to $429.99

- [x] Update name to Dyson AirWrap Styler from Sephora

- [x] Add * to "Click to shop" and "Swipe to shop", and * in front of "NO PURCHASE NECESSARY" legal at bottom.
so: "Click to shop* for a chance to win", "Swipe to shop* for a chance to win" and "*NO PURCHASE NECESSARY"

- [x] Add (optional) to Let's stay in **touch?** 

- [x] **FACEBOOK SHARE COPY**: I entered for a chance to win @Klarna’s 48 Hr. Smoooth Room. Now, I’m helping my friends win too. I’m a good person. Click here to enter. Klarna - Swedish for smooother shopping. NO PURCH. NEC. Open to legal res of 50 US/DC, 18+ only. Begins 7/16/20 and ends 12PM 7/18/20. For Rules, visit https://bit.ly/2By2n9V. Void where prohibited. Msg&data rates may apply.

- [x] **TWITTER SHARE COPY**: I entered for a chance to win @Klarna’s 48 Hr. Smoooth Room. Now, I’m helping my friends win too. I’m a good person. Click here to enter. Klarna - Swedish for smooother shopping.  No Purch. Nec. Ends 12PM 7/18/20. 18+, US only, Rules: https://bit.ly/2By2n9V.

- [x] Up the font-size of the rules footer. They said no specific size but it was just not legible -- too small. let's bump it up another point.

- [x] NEW RULES AND
[PL013823_Klarna Smoooth Room Sweepstakes_Official Rules_6.25.20 (1).docx](https://github.com/wildlifela/klarna-smoooth-shoppability/files/4834051/PL013823_Klarna.Smoooth.Room.Sweepstakes_Official.Rules_6.25.20.1.docx)
 LEGAL.  Doc attached.

**Comment by zerostyle** [comment]
@janell-f For:

"Add * to "Click to shop" and "Swipe to shop", and * in front of "NO PURCHASE NECESSARY" legal at bottom.
so: "Click to shop* for a chance to win", "Swipe to shop* for a chance to win" and "*NO PURCHASE NECESSARY""

Do I use `click` and `swipe' for mobile?

**Comment by janell-f** [comment]
Click for desktop
Swipe for mobile
