### ISSUE TITLE
[Countdown] Day Marker

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#131]
You were right, we need a day marker on the countdown. 

Can we make it
Days  - - Hours - - Minutes - - Seconds

Please and thank you

**Comment by zerostyle** [comment]
That looks pretty bad. Suggestions to fix?

<img width="515" alt="Screenshot 2020-06-25 13 24 48" src="https://user-images.githubusercontent.com/185137/85805174-4c2dec00-b6e7-11ea-90ff-86e7e0fbbf45.png">

**Comment by friedman74** [comment]
@janell-f will they care if we change days/hours/mins/secs to be much smaller, similar to the main smoooth room?

**Comment by zerostyle** [comment]
The main room count down does not have days, so it's still an issue to solve for.

**Comment by janell-f** [comment]
Sorry! I meant Days Hours Minutes Seconds as the format, we can keep the marker titles as they were in the PSDs: https://drive.google.com/drive/u/1/folders/1--KuOiSFDqSnDveDjSSOCa1DQgnzDb7Q

Maybe it's Day. Hr. Min. Sec. ?

**Comment by friedman74** [comment]
I'm saying the font size getting much smaller would help on the days/hours/etc. text, could be waaay smaller?

**Comment by janell-f** [comment]
I don't think the copy get get _much_ smaller.  Maybe we can space it out?

**Comment by zerostyle** [comment]
Does this work?

<img width="428" alt="Screenshot 2020-06-25 13 56 47" src="https://user-images.githubusercontent.com/185137/85806768-b9438080-b6eb-11ea-8e5a-b9fcc4f5eade.png">

**Comment by friedman74** [comment]
That works for me, can see if client approves

**Comment by zerostyle** [comment]
I remove the day count when it's under 24 hours.
