### ISSUE TITLE
Limit scrolling to left to not see empty background

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#15]
Can we prevent users from scrolling left to reveal the broken images/edge of the site. Occurs on mobile as well to a smaller degree.

![image](https://user-images.githubusercontent.com/20975193/83701283-0b4a2800-a5be-11ea-8d82-44dc36a13b35.png)

@janell-f @friedman74

**Comment by zerostyle** [comment]
Yes. I just need to add more background the site.
