### ISSUE TITLE
[Desktop] || Swipe is sticky

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#18]
**Logging this for later, we're only working on mobile today**

Swiping/Clicking and dragging on desktop is feeling really sticky.  Check out the video attached.

Chrome browser.

https://drive.google.com/file/d/1QBvLxYBpDmmlDoXiNbmPYQTKzcKYllvE/view?usp=sharing

**Comment by zerostyle** [comment]
Dragging is not really a desktop paradigm. I think the site will benefit from a secondary navigation. I think one is being designed.

**Comment by janell-f** [comment]
Roger that! Closing this out then.
