### ISSUE TITLE
Type - animate off on swipe

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#22]
Is it possible to animate the type off in the same way it comes on as you navigate away from each object? So it doesn’t just pop off if you go back to the home position and there’s more of an animation change among the object names/description as you navigate?

@janell-f @friedman74

**Comment by zerostyle** [comment]
Is this happening both mobile and desktop?

**Comment by zerostyle** [comment]
This is complicated and will take some time to investigate.

**Comment by zerostyle** [comment]
This is fixed.
