### ISSUE TITLE
[Tracking Pixels] 

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#23]
Please see the description and pixels attached for the Smooth room campaign site.

For Snap, Facebook and Campaign Manager, please use events & variables when sending URLs into the pixel(s) so we can separate from our side. For Google ads we can set rules in the system.

**Snapchat**
Set Up Your Snap Pixel
Snapchat Pixel ID - 675a917f-06da-4be8-9591-91c5efebda31

**Add the Pixel to your Website**
Find the <head></head> tags near the top of your website. If you are using a CMS or web platform try looking for header template. Copy the Pixel snippet below and paste it into the <head></head> of your website.

Send page URL PAGE_VIEW to separate pages on smoooth.klarna.com

**Event Type**: PAGE_VIEW
**Description**: Track webview pages
**Example**: snaptr('track', 'PAGE_VIEW')

**Facebook**
Copy and paste the pixel code into the bottom of the header section of your site, just above the </head> tag. Install the base code on every page 
 
**Google ads**
Copy the tag and paste it in between the <head></head> tags of every page 
 
**Campaign Manager**
How to implement the global snippet:
Insert the global site tag between the <head> and </head> tags. The global snippet section should be placed on every page
 
**How to implement the event snippet:**
The event snippet section should be placed on pages with events you’re tracking, after the global snippet.
Send page URL in 'u13': '[URLs]' - so we can separate URLs on our side

[fwdpixelsforsmoothroomklarna.zip](https://github.com/wildlifela/klarna-smoooth-shoppability/files/4731725/fwdpixelsforsmoothroomklarna.zip)

**Comment by janell-f** [comment]
Hey Josh, new snapchat pixel.  Can we make sure these are dropped in this morning? 

[Snapchat.txt](https://github.com/wildlifela/klarna-smoooth-shoppability/files/4766287/Snapchat.txt)

**Comment by janell-f** [comment]
Regarding the CM pixel. Seems like the page URL is missing in the URLs. In bold below. Possible to change to page URLs in the tag?

Now:
u13=[URLs]

Should be:
u13=[pageURLs]

Can we update this?

**Comment by pr1ntr** [comment]
Each of these pixel codes rely on a unique url, since the experience does not actually reload page to page, we'll just have to put all the <script> tags in the head and call each individual function every time the page changes.
