### ISSUE TITLE
[Sweepstakes] Need a way back to product after tapping "I want that"

### ISSUE THREAD

**Issue by friedman74** [wildlifela/klarna-smoooth-shoppability#24]
I'm realizing we have no way to close the "4 payments of nothing" and name/email fields, other than swiping away to a different product.

Feels like we probably need an X in the top right corner of the pink band? Or at a minimum tapping outside of the pink bottom overlay area should close?

cc @janell-f @scottiedarko

**Comment by zerostyle** [comment]
What about on desktop? Maybe a close action is not needed, it auto closes when you move to a new product in the slider.

**Comment by friedman74** [comment]
right, you don't feel "blocked" by the UI on desktop the way the pink overlay that comes up sort of pulls you out of the room, slightly, on mobile..
