### ISSUE TITLE
[Swipe] | Each swipe should pause on an object 

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#25]
On mobile, so we pause on each of the prizes

**Comment by friedman74** [comment]
I think the spirit of their note is, ideally, to just make it harder to skip past items as you scroll, but not lose the nice feeling of momentum and control that we have currently in the build. They just feel it's a little too easy to fly past items, so it's just adding a bit more scroll resistance, if possible.

**Comment by zerostyle** [comment]
I made a little adjustment, let me know how that feels.

**Comment by friedman74** [comment]
Helping a little bit, think we could push it a little more even?

**Comment by zerostyle** [comment]
More felt too stiff to me, but I can post it for you to try.

**Comment by janell-f** [comment]
@friedman74 are you liking the swipe, can I close this ticket?

**Comment by friedman74** [comment]
yea, i don't think we could push it much further than we did, feels pretty good, they can comment further from here if needed
