### ISSUE TITLE
[Products] | Hover

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#26]
[I know we posted about this in slack, but want to keep things organized]

Can we make the prizes hover slightly?  We'll only be getting 2D assets, so a slight hover/shadow, no rotation.

@scottiedarko any other notes for hover?

**Comment by scottiedarko** [comment]
Great job implementing this. It sounds like now they want to make it so the object rises up and scales slightly towards the user as the user lands on the item. Reference video for how I picture that attached.

@janell-f do they still want it to also levitate?

**Comment by janell-f** [comment]
Yup! Still want it to levitate.

**Comment by zerostyle** [comment]
Can I get access to that drive folder?

**Comment by scottiedarko** [comment]
granted!

**Comment by zerostyle** [comment]
That's going to be tricky. I'll look in to it.

**Comment by scottiedarko** [comment]
This works well @zerostyle can we just keep the smallest size of the prize a little larger so it doesn't shrink quite so much as you move away? increase minimum size by 50%?
