### ISSUE TITLE
[Landing] What's Klarna link

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#27]
**Copy was updated, so it's What's Klarna? not What's A Klarna?"**

We can drop this in, and there will be a pop up: 

Link copy: What's Klarna?
Popup copy: Klarna is a new online shopping app from Sweden. With Klarna, you can shop any online retailer and pay for your purchase in four interest-free payments, get customized price drop alerts and deals on the things you love, and shop online smooother than ever before.

![Screen Shot 2020-06-10 at 3 12 08 PM](https://user-images.githubusercontent.com/58711192/84324108-e826f780-ab2c-11ea-9212-080df06eae0b.png)

**Comment by janell-f** [comment]
Looks good! This should say "What's Klarna?" not "What's a Klarna?"

**Comment by janell-f** [comment]
Copy on pop up should be: 

Klarna is a new online shopping app from Sweden. With Klarna, you can shop any online retailer and pay for your purchase in four interest-free payments, get customized price drop alerts and deals on the things you love, and shop online smooother than ever before.

**Comment by zerostyle** [comment]
Fixed
