### ISSUE TITLE
[Prize overlap when keyboard appears]

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#29]
On Android (Pixel 2XL)

When the keyboard comes up, the prize also rises, overlapping with the copy and Klarna logo. Upper left hand corner. 

Video attached. 

[20200610-161437-720x1440.mp4.zip](https://github.com/wildlifela/klarna-smoooth-shoppability/files/4761700/20200610-161437-720x1440.mp4.zip)

**Comment by zerostyle** [comment]
I'm not sure how to fix this. The positioning is based on the viewport height and the viewport shrinks.

**Comment by janell-f** [comment]
Copy that - I think we can cover this one tomorrow, and caveat it
