### ISSUE TITLE
[Copy] | Prize Headline

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#30]
This will apply to all prizes: 

PRIZE NAME
"Smoooth Room Price Drop: You can win this prize, for free"
[strikeout price] $0

**Comment by scottiedarko** [comment]
no more item description?

**Comment by janell-f** [comment]
No more description

**Comment by zerostyle** [comment]
The comps have "Klarna Price Drop Alert:"

What is correct?

<img width="344" alt="Screenshot 2020-06-11 09 18 20" src="https://user-images.githubusercontent.com/185137/84429816-7f8b5980-abc4-11ea-9d30-beda92d357b7.png">

**Comment by scottiedarko** [comment]
@janell-f is their copy deck the latest? it says:

**Smoooth Room Price Drop: You can win this <PRIZE>, for free.**

**Comment by scottiedarko** [comment]
also on the subject of prize headline styling:

Prize Item Names: Please use Klarna Sans Bold for prize names instead of Klarna Headline

**Comment by scottiedarko** [comment]
can we show the black price and then see the price drop pink bar and THEN see the new price reducing?

**Comment by zerostyle** [comment]
@scottiedarko Can you clarify 'reducing'?

**Comment by scottiedarko** [comment]
"reducing" as in the price change from $300 to $0, not size but just the price value change.

**Comment by zerostyle** [comment]
So it animates from 300 to zero?

**Comment by zerostyle** [comment]
Also are we removing the strike though the price? Trying to visualize all the states in my head without a graphics.

**Comment by scottiedarko** [comment]
> $300 price appears 
> Price drop alert bar appears and covers the 300
> Price drop bar animates away
> 300 price is visible again and gets a strike through and the white $0 animates on

**Comment by scottiedarko** [comment]
Also when the copy says you can win this prize for free; it’s meant to be:

You can win this <insert prize name here> for free. So can we put “necklace” or “teenage engineering op-1” or “flamingo” for free.
