### ISSUE TITLE
[Share] | Mobile

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#31]
On mobile, wouldn't share launch the native options? 

![Screenshot_20200610-143400](https://user-images.githubusercontent.com/58711192/84335428-abb5c480-ab49-11ea-9435-215ab5f03eba.png)

**Comment by zerostyle** [comment]
It detects if the feature is supported in each browser, and choose how to share.

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

<img width="1054" alt="Screenshot 2020-06-11 08 56 33" src="https://user-images.githubusercontent.com/185137/84428021-79e04480-abc1-11ea-94c8-bdae3fdb1116.png">

**Comment by janell-f** [comment]
Hmmm, odd, I thought this would have popped up the drawer with the available sharing methods.

**Comment by friedman74** [comment]
i get the same result on iOS, shows me the copy link box that i'd expect on desktop rather than mobile share api..

**Comment by zerostyle** [comment]
This will fail if the site is served via `http`. It must be `https`.

**Comment by friedman74** [comment]
ahh 💡
