### ISSUE TITLE
[Loading Animation] | Remove

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#36]
Should we remove the loading animation?  Initially, Klarna was going to ask for a more complicated/additional step loading animation, and if they see one, they might ask if we can make it really elaborate. 

@scottiedarko what do you think?

**Comment by scottiedarko** [comment]
yeah i think take out that spinning spiral thing for now and just show a blank pink screen and the klarna logo if we need something on screen while it loads.
