### ISSUE TITLE
[Copy] Smooth > Smoooth

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#39]
Let's get another o in Smooth, so it's Smoooth:

![Screenshot_20200611-183910 copy](https://user-images.githubusercontent.com/58711192/84455811-27c80f00-ac13-11ea-8a99-a3e62d94b59f.png)

**Comment by friedman74** [comment]
Should the Download Klarna button be here as well?

**Comment by janell-f** [comment]
Oh, good call - probably.

**Comment by zerostyle** [comment]
Fixed
