### ISSUE TITLE
Collapsing Arrow

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#40]
Should this arrow be bottom center? 

![Screenshot_20200611-183910](https://user-images.githubusercontent.com/58711192/84455837-38788500-ac13-11ea-8687-832ede5e17fb.png)

**Comment by zerostyle** [comment]
Most recent comps have it at the top.

<img width="348" alt="Screenshot 2020-06-11 15 44 57" src="https://user-images.githubusercontent.com/185137/84455972-85039680-abfa-11ea-875d-99bfc4f06ede.png">

**Comment by friedman74** [comment]
At the bottom center I think it indicates scrolling down for more, but it’s really the “collapse this overlay” option. I’m not sure why they don’t want an X but I think whatever it is makes sense up there for now.

**Comment by janell-f** [comment]
Agreed, it feels arbitrary.  I like this as an option!
