### ISSUE TITLE
[Desktop] Share panel - layout adjustments

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#47]
Can we touch up the Entry completed/Share panel window that slides out so it's width is larger and the layout is adjusted a bit like the attached?

- [x] pink panel width extends to the right more for a closer 50/50 split of the window space
- [x] Add Klarna logo top right
- [x] add Back to room in bottom left corner
- [x] add Learn more on right edge, same margin space as Back to Room
- [x] left align Share your new Swedish friend with your friends type
- [x] left align social logos and scale up social logos
- [x] increase size of Help your friends with something. headline and put lower, closer to middle
- [x] adjust placement of Download Klarna button, larger and left aligned, higher up closer to headline
- [x] remove X from top right panel, "back to room" achieves this function now
- [ ] as per other desktop tickets, scale up prize/pillar and ensure horizontal placement is centered in view of room

@janell-f @friedman74 
![Klarna_desktop_share_panel_layout_size](https://user-images.githubusercontent.com/20975193/84535375-8daea800-aca0-11ea-9788-766b0ddb00fc.jpg)

**Comment by zerostyle** [comment]
Going to close this. We can track progress of the last item in the list in this issue: https://github.com/wildlifela/klarna-smoooth-shoppability/issues/46
