### ISSUE TITLE
[Share] | Randomized Links

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#48]
When we share to social, the items that we share should be randomized to different prizes.

**Comment by zerostyle** [comment]
Not sure what this means, can you clarify?

**Comment by janell-f** [comment]
When someone shares, the link should be random for any of the products.  So if someone shares, the link would be a deep link to any of the products. 

The more I say this out loud the more it sounds like a strange idea.  @friedman74 wdyt? I know this was specific, but it feels so weird to me to drop someone on a specific prize and not the home page

**Comment by friedman74** [comment]
Right, a bit odd to not land on the intro screen if you're just discovering this campaign...

Maaybe we could randomize the OG share image if they supplied multiple? Though that might be more work than we want to put on ourselves.

**Comment by janell-f** [comment]
Yeah, I just chatted with Natalie, and it sounds like just landing on this was an enormous battle, so randomized links on sharing is the final direction.

**Comment by friedman74** [comment]
@zerostyle do we have support to deep link to products atm?

**Comment by zerostyle** [comment]
Working on that now, I'm almost done.

**Comment by zerostyle** [comment]
I'm not 100% clear on this. So when we share, we randomly select a product and append that id to the URL?

**Comment by zerostyle** [comment]
Deep links is done.

**Comment by friedman74** [comment]
yes. so it will randomly set the OG:url to either..

smoooth.klarna.com/aquarium, or smoooth.klarna.com/dope-gaming-chair, or /kayak, or whatever the prize/URL names end up being.

**Comment by janell-f** [comment]
Just want to make sure this is working - trying sharing, and didn't see that we were landing on random prizes.

**Comment by janell-f** [comment]
Let's nix this.  The client saw it in action, and it looks like a bug.  When sharing through FB, Twitter, or general share, it should link out to smoooth.klarna.com

**Comment by zerostyle** [comment]
Haha. Nixed.

**Comment by janell-f** [comment]
Let's double check that this is nixed.  Social should only share to the main landing page: https://smoooth.klarna.com/

![Screenshot_20200626-145110](https://user-images.githubusercontent.com/58711192/85904578-faa46080-b7bd-11ea-9529-33cbb7d37578.png)

**Comment by zerostyle** [comment]
Currently is sharing the URL, but I can fix it to the homepage.
