### ISSUE TITLE
[Addition Submissions]

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#5]
Hey Pav - wanted to consolidate thoughts to figured out what LOE looks like to give users an additional entry to win an item if they've shared the experience. 

https://docs.google.com/presentation/d/1KSnUGVCFy04Xc8GilNH2uC8xeTaZMkwCSus0FpvBzcw/edit?ts=5ecd462a#slide=id.g8749de1a63_0_15

Let me know what you think.  It feels like it's one more step, and makes it feel less smoooth, but let me know your thoughts.

**Comment by friedman74** [comment]
Perhaps there are two approaches.

One is the whole Twitter login auth thing which is kinda clunky and definitely not smoooth or easy, and the other is just adding it to the entry as soon as the user clicks a share icon, giving them benefit of the doubt for doing that much, which would avoid us having to bring in the Twitter app auth step or tie that back to a submission.

**Comment by janell-f** [comment]
If we all agree, I can respond.  Are there additional hours to consider here?

**Comment by friedman74** [comment]
Yes, either way this is additional scope. I don't think we need to spend time costing that out at this stage though, since conceptually we are recommending against this.

**Comment by janell-f** [comment]
Awesome, thanks
