### ISSUE TITLE
[Enter] Rearranged layout of 'Agree' and 'Submission' screens

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#54]
Klarna designed this, but I don't have PSDs :( 

Is if possible to match these references?  

**COPY UPDATE TOO**
instead of four payments of nothing, it will be four payments of $0

![Screen Shot 2020-06-15 at 12 26 32 PM](https://user-images.githubusercontent.com/58711192/84698083-0f524000-af04-11ea-8538-cef3d5f98a52.png)

**Comment by zerostyle** [comment]
I'll do my best without a PSD.

@janell-f So the copy will be?
`Agree to pay four payments of $0?`

**Comment by janell-f** [comment]
Yes!
