### ISSUE TITLE
[Confirmation Screen]

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#55]
- [x] Let's remove the timer from only this screen
- [x] Add the x back in to close. No more arrows
- [x] Stack the copy like the screenshot below
- [ ] More spacing between Download Klarna button and share icons 

![Screen Shot 2020-06-15 at 12 33 25 PM](https://user-images.githubusercontent.com/58711192/84698325-7839b800-af04-11ea-8375-02369cd3a96d.png)

**Comment by zerostyle** [comment]
I could have called this one. Put the X back. Haha.

**Comment by janell-f** [comment]
I know! The arrow was a terrible idea.

**Comment by zerostyle** [comment]
This is not the first time we've done this on a project. There is no need to reinvent the wheel on common UX. :)

**Comment by janell-f** [comment]
"But what if there's a hamburger menu" was shut down 3 times before it made it's way to dev 😂
