### ISSUE TITLE
[Social Share Copy]

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#58]
**GENERAL SHARE**
Share the Klarna 48 Hr. Smoooth Room and help your friends win, too

**PRE-POPULATED TWEET COPY:**
I may have just won @Klarna’s 48 Hour Smoooth Room. Now, I’m helping my friends win, too. I’m a good person. Click here to enter. Ends <TIME + DATE>. Klarna - Swedish for smooother shopping.

**PRE-POPULATED FACEBOOK COPY:**
I may have just won @KlarnaUSA 48 Hour Smoooth Room. Now, I’m helping my friends win, too. I’m a good person. Click here to enter. Ends <TIME + DATE>. Klarna - Swedish for smooother shopping.

_If They Try To Win Another Item..._
Sorry, one entry per human. 
Be a good friend, share the Smoooth Room now.

**Comment by janell-f** [comment]
**Final date and time added:** 

**PRE-POPULATED TWEET COPY:**
I may have just won @klarna’s 48 Hour Smoooth Room. Now, I’m helping my friends win, too. I’m a good person. Click here to enter. Ends at 11:59:59 PM ET on 7/18/20. Klarna - Swedish for smooother shopping.

**PRE-POPULATED FACEBOOK COPY:**
I may have just won @KlarnaUSA 48 Hour Smoooth Room. Now, I’m helping my friends win, too. I’m a good person. Click here to enter. Ends at 11:59:59 PM ET on 7/18/20. Klarna - Swedish for smooother shopping.

**Comment by janell-f** [comment]
Instead of "I may have just won", let's update to "I entered for a chance to win"

**Comment by zerostyle** [comment]
This is done.

**Comment by janell-f** [comment]
Need to add the rules to social share copy: 

**I entered for a chance to win @Klarna’s 48 Hr. Smoooth Room Sweepstakes. Now, I’m helping my friends win too. I’m a good person. Click here to enter. No Purch. Nec. Ends 12PM EST 7/18/20 18+, US only, Rules: bit.ly**

- Make a bit.ly link for smoooth.klarna.com/rules

**Comment by zerostyle** [comment]
Where does this go?

**Comment by janell-f** [comment]
When you share to Twitter or fb

**Comment by zerostyle** [comment]
In the body of the share text. OK.
