### ISSUE TITLE
[Set Assets] New TV, Carpet, and Background

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#61]
https://drive.google.com/drive/u/1/folders/1feD8_GFnxcH-seHEb5yUmWW_UuhjXnXR

Let's start importing the new assets.

**Comment by zerostyle** [comment]
I put them in, give it a whirl.

**Comment by scottiedarko** [comment]
New carpet and wall look good. Do we have new TV in there too?

**Comment by zerostyle** [comment]
I don't have a new asset for that.

**Comment by zerostyle** [comment]
Done
