### ISSUE TITLE
[Desktop] Click and Drag is really sticky

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#65]
Might need to finesse how click and drag is working on desktop. Currently, if I click and drag, the mouse either gets really sticky, or slides to the 5th or 6th item in the gallery

**Comment by scottiedarko** [comment]
this is odd, it doesnt generally happen for me but if you click on the prize pillar or close to it and throw, then i do experience this stickyness where it won't go to the next item.

**Comment by zerostyle** [comment]
I have not experienced this stickiness. Not sure how to fix this.

**Comment by janell-f** [comment]
I think this got better, but we also saw this on Tillamaps, where if you click and drag, and your mouse moves off the window before you release, the scroll is still sticking to the cursor.

**Comment by friedman74** [comment]
Yea I think it's been less of an issue in recent builds personally. I'm not sure it can ever be totally perfect if the user drags outside of the browser window etc but it never gets totally stuck or broken, either?

**Comment by zerostyle** [comment]
I think I might be able to fix the mouse moving out of the window. I'll look in to that.

**Comment by zerostyle** [comment]
I added some code to listen to mouse leaving the window. This does help the "stickiness". Maybe enough to close this issue?

**Comment by friedman74** [comment]
oh yea that's feeling good.

one other thought, how does everyone feel about a hand grab/grabber icon on desktop, at least while the user has clicked and held? we could keep it cursor/pointer when over the prize details, buttons, etc..

**Comment by zerostyle** [comment]
Added drag and dragging cursors.

**Comment by friedman74** [comment]
I'm liking that. If it's easy enough, can we keep it the regular cursor over the prize headline, like it is on the "You can win for $0.." text ?

**Comment by zerostyle** [comment]
Yes and done.

**Comment by friedman74** [comment]
@janell-f i think this issue can be closed but see how click+drag is feeling for you.

**Comment by janell-f** [comment]
Smooooooooooooooooooooth!!
