### ISSUE TITLE
[Desktop] Learn More

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#68]
This (and the logo) both link out to Klarna.com - do we need both @scottiedarko ?

<img width="1552" alt="Screen Shot 2020-06-15 at 7 05 50 PM copy 2" src="https://user-images.githubusercontent.com/58711192/84724070-0bdaab00-af3c-11ea-9683-c77835fc118f.png">

**Comment by friedman74** [comment]
I think it's OK since the logo is always present. Unless they were open to the logo going back to the intro/landing screen throughout the experience?

**Comment by zerostyle** [comment]
Should I remove this?

**Comment by janell-f** [comment]
Forgot to close this out.  Let's leave it.
