### ISSUE TITLE
[Desktop] Remove button outline on hover

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#70]
Can we make the hover state just a solid filled white button, remove the black outline on hover on desktop?

@friedman74 @janell-f 

![klarna_hoverstate_outline](https://user-images.githubusercontent.com/20975193/84809052-6583b980-afbe-11ea-861e-c988c8da50e2.jpg)

**Comment by zerostyle** [comment]
This is how they hover buttons are styled on Klarna.com. Are you sure you want to do that?

**Comment by scottiedarko** [comment]
oh really? then nope, let's 's leave it.
