### ISSUE TITLE
[Desktop] Form input focus box visible - Chrome Windows 10

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#71]
When I go to enter my name/email, I can see the default outline box appear that frames the actual input button, can we hide this to keep the designed styling intact?

@friedman74 @janell-f 

![klarna_form_box_visible](https://user-images.githubusercontent.com/20975193/84809343-ca3f1400-afbe-11ea-834a-b2e057505e0f.jpg)

**Comment by janell-f** [comment]
Getting the updated Sign Up copy from Mirimar
