### ISSUE TITLE
Legal / Rules need X to close out full screen overlay

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#74]
on mobile/desktop no way to get back to the main Smoooth room from the pink overlay once you click legal/conditions links 

@janell-f @friedman74

**Comment by zerostyle** [comment]
Are we creating those pages, are they links to an external page?

**Comment by janell-f** [comment]
They're giving us copy. We'll drop the copy in here, not linking out.
