### ISSUE TITLE
[Desktop] Back to room - pink overlay animate off screen by sliding left

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#76]
Can we add some animation to this pink overlay shelf going away? slide left off screen similar to how it slides onto the screen when you hit "enter" to complete entry?

@janell-f @friedman74

**Comment by zerostyle** [comment]
I tried for two hours to get this to work unsuccessfully. I came to the conclusion that I will need to refactor the code quite a bit to make this work. I'm going to circle back to this one.

**Comment by zerostyle** [comment]
I had to get really creative to get this to work, but I got it. Normally an easy task but there was a lot of functionally that I kept undoing to get this to work.
