### ISSUE TITLE
1234 circle icons - style tweak

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#83]
Can we use the bolder headline font for the 1234 numbers inside the circles? Can we also scale up the number/circle icons as a unit so they're a big larger overall?

I notice as they animate there's some weird pixelation, is that because they're a font and not vector elements? anything we can do to make the animation smoother on the edges/outlines of the number characters themselves?

@friedman74 @janell-f 

![1234size](https://user-images.githubusercontent.com/20975193/84961242-a3fd9f00-b0b8-11ea-95c5-98520105aeeb.png)

**Comment by zerostyle** [comment]
Fonts are vector, so they are essentially the same as an SVG.
