### ISSUE TITLE
[Loading] Add spinner to front page?

### ISSUE THREAD

**Issue by friedman74** [wildlifela/klarna-smoooth-shoppability#85]
I think we might need the same slick spinner from the submission form, added under the Klarna logo.. with clear cache it's a pretty long load now and people might think it's just the logo and give up.

Is there more we can do to optimize the assets that would also help? Further crunching any png's with tinypng.com or the like? I assume we are only loading the flag sprites after the rest of the elements have loaded, so it might be still when someone first lands but we don't have to hold up load for it?

cc @scottiedarko @janell-f

**Comment by zerostyle** [comment]
There is more I can do. I will spend some more time with this.

**Comment by zerostyle** [comment]
I added a spinner and staggered the loading of some assets. Optimizing individual assets is what is left.

**Comment by zerostyle** [comment]
I optimized with tinypng.com. That helped a lot. There may be more we can do, so I will leave this open.

**Comment by zerostyle** [comment]
I added responsive images bases on breakpoints. I think that is all I can do!

**Comment by friedman74** [comment]
feeling speedy for me lately!
