### ISSUE TITLE
[Mobile] Prize & Pillar sizing - iPhone X - Safari

### ISSUE THREAD

**Issue by scottiedarko** [wildlifela/klarna-smoooth-shoppability#9]
Can we try scaling up the prize pillar and prize itself about twice as large to get closer to our sizing in design?

This can help push our type up higher as well 
![mobile_pillar_prize_size](https://user-images.githubusercontent.com/20975193/83552690-0783ac00-a4bf-11ea-99e1-87e992e9fefd.jpg)

@janell-f @friedman74

**Comment by zerostyle** [comment]
So it's OK that product and text overlap?

**Comment by friedman74** [comment]
we do want to avoid that, hopefully we can by tightening the padding around the logo etc so the headlines move up, plus the share popup won't be so tall once it's fully styled?

**Comment by zerostyle** [comment]
2x bigger will cause issues at certain sizes. I made it a little bigger yesterday. I think this kind of adjustment is best done when we have all the actual products. Are the items I have in the just placeholder?

**Comment by friedman74** [comment]
Yea, final assets may change a bit. I think the idea is get it as big as we can without hurting readability. Can we just get it a little bigger for now but not spend too much time perfecting, knowing the products will change?
