### ISSUE TITLE
[QA] Overlap 

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#90]
Copy is poking out a bit behind the pop up

<img width="1129" alt="Screen Shot 2020-06-18 at 2 59 25 PM" src="https://user-images.githubusercontent.com/58711192/85076087-5e9ea780-b174-11ea-8a92-5a9c238941cc.png">

**Comment by friedman74** [comment]
maybe we pad the size of that box just 5-10px more as well? feels like the X could enjoy more breathing room from the edge of the container, perhaps
