### ISSUE TITLE
Shorten distance between pedestal and prize

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#91]
Can we shorten this height?  It's coming up just a beat too high

![Screen Shot 2020-06-18 at 2 43 23 PM](https://user-images.githubusercontent.com/58711192/85074895-27c79200-b172-11ea-8f92-4a4d72a430b8.png)

**Comment by zerostyle** [comment]
We should dial this in with the actual prizes.

**Comment by janell-f** [comment]
Actual prizes received! 12/15 so far

**Comment by zerostyle** [comment]
@janell-f How does it look now?

**Comment by janell-f** [comment]
Is it updated on dev?

**Comment by zerostyle** [comment]
Yes!

**Comment by janell-f** [comment]
Looks awesome!!
