### ISSUE TITLE
[Question] Is it possible to have the carousel return to the beginning after the last product

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#96]
I know we chatted about this in slack briefly, and we would have built this differently to account for this option, but want to double check and make sure that's where we've landed, and we can't do it now.

**Comment by friedman74** [comment]
Did they ever see the design with the back to start icon etc?

**Comment by janell-f** [comment]
Yeah, that's on dev (the link we shared)

**Comment by zerostyle** [comment]
We can go back to the first slide, no problem. Looping seamlessly is much more difficult task. I'm not sure how to accomplish that at this point.

**Comment by friedman74** [comment]
@janell-f there is no icon visible currently on dev, just an empty pedestal so maybe that was partially throwing them off?

**Comment by janell-f** [comment]
Ohh!! Possibly!

**Comment by zerostyle** [comment]
I had an icon there, it's missing.

**Comment by zerostyle** [comment]
It's fixed. I got killed when I scaled in and out of each image on the change of slides.
