### ISSUE TITLE
[Entry] Pink Background

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#97]
Client's worried about any legibility issues.  Could we have the pink background be present the way we have it on the confirmation screen? 

![Screen Shot 2020-06-18 at 4 00 25 PM](https://user-images.githubusercontent.com/58711192/85079991-f30d0800-b17c-11ea-9afd-a3e44773fd70.png)

**Confirmation screen:** 

![Screen Shot 2020-06-18 at 4 03 04 PM](https://user-images.githubusercontent.com/58711192/85080124-41baa200-b17d-11ea-893b-c5533b2de2ee.png)

**Comment by zerostyle** [comment]
This is going to take some considerable work.

**Comment by janell-f** [comment]
Do you think it's doable by Monday EOD-ish?

**Comment by zerostyle** [comment]
Just noting here that we talked about this in Slack and are going to push back.

**Comment by zerostyle** [comment]
Pushed up some responsive work for laptop type screens. Hopefully this will help.

**Comment by janell-f** [comment]
Heard back from Mirimar, Klarna for sure wants to have that pink background in behind entry :/

**Comment by zerostyle** [comment]
That's fine, can we discuss how we want to handle the design changes?

**Comment by friedman74** [comment]
I think the assumption is the headlines/logo will shift left so that we can stay more consistent with the current success/pink overlay view. Happy to jump on a quick call to speak through that more as well..

**Comment by zerostyle** [comment]
OK. With this interaction the pink overlay will cover the logo and title from the room. The same logo and title will then show up, but it will be offset to the left to fit inside the pink overlay. Just double checking this is what you want. It's kinda strange, but I'm more than happy to do it.

**Comment by janell-f** [comment]
FILE IT UNDER: WIN!
