### ISSUE TITLE
[Prizes!] Asset + Links

### ISSUE THREAD

**Issue by janell-f** [wildlifela/klarna-smoooth-shoppability#98]
We have PRIZES! So far, we have the first 12. 

https://drive.google.com/drive/u/1/folders/1quqs8UykMrmj8aouszd2E_VmEKVXZeL-

**We'll also need to create a deep link for each of these prizes**

**Comment by zerostyle** [comment]
What about $ amount?

**Comment by janell-f** [comment]
Shit, thank you, working on it now

**Comment by janell-f** [comment]
Hey Josh! 

Check out this doc: 

3 titles (in bold) have been updated
Original prices
One description: 
https://docs.google.com/spreadsheets/d/1LEpkQ6b51FqJwYbZdzn1nRibDkTkPGQxLFWdU4DmAl8/edit#gid=1961947145

Still waiting on the final 3 prizes.

**Comment by janell-f** [comment]
Add a comma between 1 and 3 on the kayak's price
Add a comma between 2 and 2 on the hydrow rower price

**Comment by janell-f** [comment]
Two more prizes added! https://docs.google.com/spreadsheets/d/1LEpkQ6b51FqJwYbZdzn1nRibDkTkPGQxLFWdU4DmAl8/edit#gid=1961947145

**Mejuri 14k Gold Bangle - $485.00
Adidas ZX 4000 4D - $200.00**

Waiting on the 15th and final prize.

**Comment by zerostyle** [comment]
Do we have images for those?

**Comment by janell-f** [comment]
Yup!! Folder linked int he last comment

**Comment by zerostyle** [comment]
I don't see the images, can you post them somewhere else?

**Comment by janell-f** [comment]
One final image pending, leaving this open

**Comment by janell-f** [comment]
Final prize image: 

https://drive.google.com/file/d/1YS79Asjc4NxwticcEVqWh0ADX2jkpyD_/view?usp=sharing 

Lunya Washable Silk Pant Suit

Image below in case Drive is being funny. 
![Lunya Washable Silk Pant Suit](https://user-images.githubusercontent.com/58711192/85484164-24ba1080-b57b-11ea-98f0-a340aedf3c2a.png)
